---
# Copyright 2025 Eduardo Santos. All Rights Reserved.
name: tox
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/tox.yaml
      - tox/**
  workflow_dispatch: {}
permissions: {}
defaults:
  run:
    shell: sh
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tox:
    runs-on:
      - ubuntu-latest
    steps:
      # TODO(edcsnt): Replace docker-login(1) and docker buildx build
      # with buildah-build(1) and buildah-push(1) once Ubuntu 26.04 LTS
      # is released.
      # yamllint disable rule:line-length
      - run: |
          curl -O \
          https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ github.ref_name }}/${{ github.workflow }}/Containerfile
          docker login -u ${{ secrets.USER }} -p ${{ secrets.PASS }}
          docker buildx build \
          -f Containerfile \
          --push \
          -t \
          docker.io/${{ github.repository_owner }}/${{ github.workflow }}:latest \
          .
      # yamllint enable rule:line-length
    timeout-minutes: 1
